on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    uses: gardenlinux/package-build/.github/workflows/build.yml@main
    with:
      release: ${{ github.ref == 'refs/heads/main' }}
      build_dep: |
        gardenlinux/package-perl 5.42.2-3gl0+bp1877
        gardenlinux/package-libclone-perl 0.47-1gl0+bp1877
        gardenlinux/package-libhtml-parser-perl 3.83-1gl0+bp1877
        gardenlinux/package-ssleay-perl 1.94-3gl0+bp1877
